GET http://127.0.0.1:8000

###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{"username": "testing2", "password":"testing321","email":"example@email.com"}

###

POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "testing2", "password":"testing321"}
